# Generated by Django 3.2.3 on 2021-06-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_rename_comment_comment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
